---
version: '3'

services:
  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  heap-group:
    container_name: heap-group
    image: sanhidalgoo/heap-group:latest .
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - DB_HOST=
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
...