name: "\U0001F41E Report a problem"
description: "Report an issue"
title: "Bug: (fill in)"
labels:
  - bug
body:
- type: markdown
  attributes:
    value: Thanks for leaving us your bug report!
- type: textarea
  attributes:
    label: Environment
    description: 
    value: |
        Node version: 
        npm version: 
        Local ESLint version: 
        Global ESLint version: 
        Operating System: 
  validations:
    required: true
- type: dropdown
  attributes:
    label: Is it affecting [thecraftbeer.tk](thecraftbeer.tk)?
    description: This bug affects the main page.
    options:
      - "Yes"
      - "No"
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you do or what did you see?
    description: |
      Please include a *minimal* reproduction case. You can use Markdown in this field.
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you expect to happen?
    description: |
      You can use Markdown in this field.
  validations:
    required: true
- type: textarea
  attributes:
    label: What actually happened?
    description: |
      Please copy-paste the actual ESLint output. You can use Markdown in this field.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional comments
    description: Is there anything else that's important for the team to know?
